[project]
name = "invoice-extraction-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google>=3.0.0",
    "google-auth>=2.40.3",
    "pandas>=2.3.0",
    "streamlit>=1.45.1",
]
